# Generated by Django 4.0.8 on 2024-07-01 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_customer_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('card_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_type', models.CharField(choices=[('VISAPAY', 'VisaPay'), ('RAZZERGOLD', 'RazzerGold'), ('ITUNES', 'iTunes Card')], max_length=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('settled', models.BooleanField(default=False)),
                ('accounts_paid_into', models.ManyToManyField(blank=True, to='emsapp.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsapp.customer', to_field='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SWAP', 'Swap')], max_length=4)),
                ('coin_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('settled', models.BooleanField(default=False)),
                ('account_paid_into', models.ManyToManyField(blank=True, to='emsapp.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsapp.customer', to_field='phone_number')),
            ],
        ),
    ]
