# Generated by Django 5.0.6 on 2024-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0003_giftcardtransaction_cryptotransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="total_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="total_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
