# Generated by Django 5.0.6 on 2024-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0005_cryptotransaction_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptotransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="giftcardtransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
