# Generated by Django 5.0.6 on 2024-07-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0006_alter_cryptotransaction_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptotransaction",
            old_name="account_paid_into",
            new_name="accounts_paid_into",
        ),
    ]
