# Generated by Django 5.0.6 on 2024-07-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emsapp",
            "0007_rename_account_paid_into_cryptotransaction_accounts_paid_into",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="deferred_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="settled_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="deferred_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="settled_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
