# Generated by Django 5.0.6 on 2024-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0008_cryptotransaction_deferred_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
