# Generated by Django 5.0.6 on 2024-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0009_customer_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
