# Generated by Django 5.0.6 on 2024-09-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0010_alter_customer_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="displayname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="giftcardtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell"), ("SWAP", "Swap")],
                max_length=4,
            ),
        ),
    ]
