# Generated by Django 5.0.6 on 2024-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emsapp", "0011_customer_displayname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="payment_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="payment_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
